config/routes.rb
Aafes::Application.routes.draw do
  resources :transactions

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  resources :users
  resources :user_sessions

  resources :clients do
    resources :transactions do
      resources :approvals
      resources :settlements
      resources :credits
    end
  end
  
  match "/logout", :to => "user_sessions#destroy"
  match "/login", :to => "user_sessions#new"
  
  root :to => "pages#index"
end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to(:user)
  belongs_to :transaction
  validates_presence_of(:user_id)
  validates_presence_of(:transaction_id)
  validates_presence_of(:amount)
  
  using_access_control
  
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_filter :load_client
  before_filter :load_transaction
  filter_resource_access
  
  # GET /approvals
  # GET /approvals.xml
  def index
    @approvals = @transaction.approvals.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @approvals }
    end
  end

  # GET /approvals/1
  # GET /approvals/1.xml
  def show
    @approval = @transaction.approvals.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @approval }
    end
  end

  # GET /approvals/new
  # GET /approvals/new.xml
  def new
    @approval = @transaction.approvals.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @approval }
    end
  end

  # GET /approvals/1/edit
  def edit
    @approval = @transaction.approvals.find(params[:id])
  end

  # POST /approvals
  # POST /approvals.xml
  def create
    @approval = @transaction.approvals.new(params[:approval])

    respond_to do |format|
      if @approval.save
        format.html { redirect_to(client_transaction_approval_path(@client, @transaction, @approval), :notice => 'Approval was successfully created.') }
        format.xml  { render :xml => @approval, :status => :created, :location => @approval }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @approval.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /approvals/1
  # PUT /approvals/1.xml
  def update
    @approval = @transaction.approvals.find(params[:id])

    respond_to do |format|
      if @approval.update_attributes(params[:approval])
        format.html { redirect_to(client_transaction_approval_path(@client, @transaction, @approval), :notice => 'Approval was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @approval.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /approvals/1
  # DELETE /approvals/1.xml
  def destroy
    @approval = @transaction.approvals.find(params[:id])
    @approval.destroy

    respond_to do |format|
      format.html { redirect_to(client_transaction_approvals_url(@client, @transaction)) }
      format.xml  { head :ok }
    end
  end
  
  private
    def load_client
      @client = Client.find(params[:client_id])
    end
    
    def load_transaction
      @transaction = @client.transactions.find(params[:transaction_id])
    end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/_form.html.haml
= semantic_form_for [@client, @transaction, @approval] do |f|
  = f.input :cc_number
  = f.input :amount
  = f.input :transaction
  = f.commit_button :label => "Submit"

app/views/approvals/edit.html.haml
%h1.left-margin Editing approval
= render 'form' 

app/views/approvals/index.html.haml
%h1 Listing approvals
= link_to 'New Approval', new_client_transaction_approval_path(@client, @transaction)

%table
  %tr
    %th Card Number
    %th Amount
    %th Actions
  - @approvals.each do |approval|
    %tr
      %td= approval.cc_number
      %td= approval.amount
      %td
        = link_to 'Show', client_transaction_approval_path(@client, @transaction, approval)
        = link_to 'Edit', edit_client_transaction_approval_path(@client, @transaction, approval)
        = link_to 'Destroy', client_transaction_approval_path(@client, @transaction, approval), :confirm => 'Are you sure?', :method => :delete

app/views/approvals/new.html.haml
%h1.left-margin New approval
= render 'form'

app/views/approvals/show.html.haml
%p
  %label Card Number
  %span= @approval.cc_number
  
%p
  %label Amount
  %span= @approval.amount
  
%p
  %label Facility Number
  %span= @approval.transaction.client.facility_number

= link_to 'Back', client_transaction_approvals_path(@client, @transaction)