config/routes.rb
Aafes::Application.routes.draw do
  resources :transactions

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  resources :users
  resources :user_sessions

  resources :clients do
    resources :transactions do
      resources :approvals
      resources :settlements
      resources :credits
    end
  end
  
  match "/logout", :to => "user_sessions#destroy"
  match "/login", :to => "user_sessions#new"
  
  root :to => "pages#index"
end

app/models/settlement.rb
class Settlement < ActiveRecord::Base
  belongs_to(:user)
  belongs_to :transaction
  validates_presence_of(:user_id)
  validates_presence_of(:transaction_id)
  validates_presence_of(:amount)
  
  using_access_control
  
  def ms_settle
    builder = Nokogiri::XML::Builder.new(:encoding=>"UTF-8") do |xml|
      xml.MSSettle(:xmlns=>"MSSettle") {
        xml.Request("ID" => transaction.order_id){
          xml.CCNumber transaction.cc_number
          xml.Amount self.amount
          xml.FacNbr transaction.client.facility_number
          xml.AuthCode transaction.auth_code
          xml.AuthTkt transaction.auth_ticket
          xml.Region ( (Rails.env == "production") ? "P" : "T" )
        }
      }
    end
    
    return_code, return_message, auth_code, auth_ticket = transaction.send_request("inXMLSettle=#{builder.to_xml}", "MSSettlement")

    if return_code == "X"
      return false, return_message
    elsif return_code == "D"
      return_message = "credit was denied and will require contact with your AAFES POC" unless return_message.present?
      return false, return_message
    elsif return_code == "A"
      return true
    end
  end
  
end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
  before_filter :load_client
  before_filter :load_transaction
  filter_resource_access
  
  # GET /settlements
  # GET /settlements.xml
  def index
    @settlements = @transaction.settlements.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @settlements }
    end
  end

  # GET /settlements/1
  # GET /settlements/1.xml
  def show
    @settlement = @transaction.settlements.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @settlement }
    end
  end

  # GET /settlements/new
  # GET /settlements/new.xml
  def new
    @settlement = @transaction.settlements.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @settlement }
    end
  end

  # GET /settlements/1/edit
  def edit
    @settlement = @transaction.settlements.find(params[:id])
  end

  # POST /settlements
  # POST /settlements.xml
  def create
    @settlement = @transaction.settlements.new(params[:settlement])
    @settlement.user = current_user
    
    if @settlement.amount.blank?
      flash[:error] = "You must provide an amount to settle."
      render :action => "new" and return
    end
    
    if @settlement.amount > (@transaction.amount - @transaction.settled_amount)
      flash[:error] = "You cannot settle for an amount larger than what has been approved."
      render :action => "new" and return
    end
    
    code_ok, message = @settlement.ms_settle

    respond_to do |format|
      if code_ok and @settlement.save
        format.html { redirect_to(client_transaction_path(@client, @transaction), :notice => 'Settlement was successfully processed.') }
        format.xml  { render :xml => @settlement, :status => :created, :location => @settlement }
      else
        flash[:error] = message
        format.html { render :action => "new" }
        format.xml  { render :xml => @settlement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /settlements/1
  # PUT /settlements/1.xml
  def update
    @settlement = @transaction.settlements.find(params[:id])

    respond_to do |format|
      if @settlement.update_attributes(params[:settlement])
        format.html { redirect_to(client_transaction_settlement_path(@client, @transaction, @settlement), :notice => 'Settlement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @settlement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /settlements/1
  # DELETE /settlements/1.xml
  def destroy
    @settlement = @transaction.settlements.find(params[:id])
    @settlement.destroy

    respond_to do |format|
      format.html { redirect_to(client_transaction_settlements_url(@client, @transaction)) }
      format.xml  { head :ok }
    end
  end
  
  private
    def load_client
      @client = Client.find(params[:client_id])
    end
    
    def load_transaction
      @transaction = @client.transactions.find(params[:transaction_id])
    end
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/settlements/_form.html.haml
%p
  %b Transaction
  = @transaction.id
  
%p
  %b User:
  = @transaction.user.email

%p
  %b Facility number:
  = @transaction.client.facility_number 

%p
  %b Order:
  = @transaction.order_id 
  
%p
  %b Card Number:
  = @transaction.cc_number

%p
  %b Auth Code:
  = @transaction.auth_code

%p
  %b Auth Ticket:
  = @transaction.auth_ticket

%p
  %b Approved Amount:
  = @transaction.amount
    
%p
  %b Settled Amount:
  = @transaction.settled_amount

%p
  %b Credited Amount:
  = @transaction.credited_amount
  
= semantic_form_for [@client, @transaction, @settlement] do |f|
  = f.input :amount, :hint => "Enter the amount you wish to settle in pennies. Example: $5 would be entered as 500.  You may settle the transaction as many times as you would like, but you may not settle for more than the approved amount."
  = f.commit_button :label => "Submit"

app/views/settlements/edit.html.haml
%h1 Editing settlement
= render 'form'
= link_to 'Show', client_transaction_settlement_path(@client, @transaction, @settlement)
|
= link_to 'Back', client_transaction_settlements_path(@client, @transaction)

app/views/settlements/index.html.haml
%h1 Listing settlements
= link_to 'New Settlement', new_client_transaction_settlement_path(@client, @transaction)
%table
  %tr
    %th
    %th
    %th
  - @settlements.each do |settlement|
    %tr
      %td= link_to 'Show', client_transaction_settlement_path(@client, @transaction, settlement)
      %td= link_to 'Edit', edit_client_transaction_settlement_path(@client, @transaction, settlement)
      %td= link_to 'Destroy', client_transaction_settlement_path(@client, @transaction, settlement), :confirm => 'Are you sure?', :method => :delete

app/views/settlements/new.html.haml
%h1 New settlement
= render 'form'
= link_to 'Back to Transaction', client_transaction_path(@client, @transaction)

app/views/settlements/show.html.haml
%p
  %b Transaction
  = @transaction.id

%p
  %label Card Number
  %span= @transaction.cc_number
  
%p
  %label Approved Amount
  %span= @transaction.amount
  
%p
  %label Facility Number
  %span= @transaction.client.facility_number
  
%p
  %label Auth Code
  %span= @transaction.auth_code
  
%p
  %label Auth Ticket
  %span= @transaction.auth_ticket

%p
  %label Settled Amount
  %span= @settlement.amount

= link_to "Credit Transaction", new_client_transaction_credit_path(@client, @transaction)
|
= link_to "View All Transactions", client_transactions_path(@client)