config/routes.rb
Aafes::Application.routes.draw do
  resources :transactions

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  resources :users
  resources :user_sessions

  resources :clients do
    resources :transactions do
      resources :approvals
      resources :settlements
      resources :credits
    end
  end
  
  match "/logout", :to => "user_sessions#destroy"
  match "/login", :to => "user_sessions#new"
  
  root :to => "pages#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :load_client
  filter_resource_access
  
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = @client.transactions

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = @client.transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = @client.transactions.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = @client.transactions.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = @client.transactions.new(params[:transaction])
    @transaction.user = current_user
    
    if @transaction.cc_number.blank? and @transaction.amount.blank?
      flash[:error] = "You must provide a card number and amount to charge."
      render :action => "new" and return
    end
    
    code_ok, message = @transaction.ms_approval

    respond_to do |format|
      if code_ok and @transaction.save
        format.html { redirect_to(client_transaction_path(@client, @transaction), :notice => 'Transaction was successfully Approved.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        flash[:error] = message
        format.html { render :action => "new", :error => message }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = @client.transactions.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(client_transaction_path(@client, @transaction), :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = @client.transactions.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(client_transactions_url(@client)) }
      format.xml  { head :ok }
    end
  end
  
  private
    def load_client
      @client = Client.find(params[:client_id])
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= semantic_form_for [@client, @transaction] do |f|
  = f.input :order_id, :hint => "Use the unique order id from your store's orders here to track your Star Card Transactions against your orders."
  = f.input :cc_number, :label => "Card Number", :hint => "Use the customers Star Card account number."
  = f.input :amount, :hint => "The amount to charge the Star Card in cents. Example $10.00 should be entered as 1000."
  = f.commit_button :label => "Submit"
  .cancel
    or
    = link_to 'cancel', client_transactions_path(@client)

app/views/transactions/_table.html.haml
= link_to 'New Transaction', new_client_transaction_path(@client), :class=>"add"
%h1 Listing Transactions
%table
  %tr
    %th Order ID
    %th Approved Amount
    %th Settled Amount
    %th Credited Amount
    %th Auth Code
    %th Auth Ticket
    %th Actions
  - @transactions.each do |transaction|
    %tr
      %td= transaction.order_id
      %td= transaction.amount
      %td= transaction.settled_amount
      %td= transaction.credited_amount
      %td= transaction.auth_code
      %td= transaction.auth_ticket
      %td
        = link_to 'Show Details', client_transaction_path(@client, transaction)
        - if transaction.settled_amount < transaction.amount
          |
          = link_to 'Settle', new_client_transaction_settlement_path(@client, transaction)
        - if transaction.credited_amount < transaction.settled_amount
          |
          = link_to 'Credit', new_client_transaction_credit_path(@client, transaction)

app/views/transactions/edit.html.haml
%h1 Editing transaction
= render 'form' 
= link_to 'Show', @transaction 
|
= link_to 'Back', transactions_path 

app/views/transactions/index.html.haml
= render 'table', :locals=>{:transactions=>@transactions}

app/views/transactions/new.html.haml
%h1 New transaction
= render 'form'

app/views/transactions/show.html.haml
%p
  %b User:
  = @transaction.user.email

%p
  %b Facility number:
  = @transaction.client.facility_number 

%p
  %b Order:
  = @transaction.order_id 
  
%p
  %b Card Number:
  = @transaction.cc_number


%p
  %b Auth Code:
  = @transaction.auth_code

%p
  %b Auth Ticket:
  = @transaction.auth_ticket

%p
  %b Approved Amount:
  = @transaction.amount

%p
  %b Settled Amount:
  = @transaction.settled_amount
  
%p
  %b Credited Amount:
  = @transaction.credited_amount

= link_to 'View All Transactions', client_transactions_path(@client)
- if @transaction.settled_amount < @transaction.amount
  |
  = link_to 'Settle Transaction', new_client_transaction_settlement_path(@client, @transaction)
- if @transaction.credited_amount < @transaction.settled_amount
  |
  = link_to 'Credit Transaction', new_client_transaction_credit_path(@client, @transaction)