config/routes.rb
Aafes::Application.routes.draw do
  resources :transactions

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  resources :users
  resources :user_sessions

  resources :clients do
    resources :transactions do
      resources :approvals
      resources :settlements
      resources :credits
    end
  end
  
  match "/logout", :to => "user_sessions#destroy"
  match "/login", :to => "user_sessions#new"
  
  root :to => "pages#index"
end

app/views/layouts/application.html.haml
!!! html5
%html
  %head
    %title AAFES Payments
    = stylesheet_link_tag "style", "smoothness/jquery-ui-1.8.4.custom"
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    - if current_user
      #page
        - if @client
          #client-info
            %b Client Name:
            = @client.name

            %b Facility Number:
            = @client.facility_number

        #logout
          = link_to "Home", root_path
          - if permitted_to? :index, :users
            |
            = link_to "Users", users_path
          - if permitted_to? :index, :clients
            |
            = link_to "Clients", clients_path
          |
          - if @client and @client.valid?
            = link_to "All Transactions", client_transactions_path(@client)
            |
            = link_to "New Transaction", new_client_transaction_path(@client)
            |
          = link_to "Logout", logout_path
        
        = clear_div
        - flash.each do |key, msg|
          = content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}"
        = yield
    - else
      #login
        - flash.each do |key, msg|
          = content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}"
        = yield